In [23]:
import pandas as pd
import geopandas as gpd
import uuid
from datetime import datetime

In [24]:
# Predefined variable for title and version

# Enter your initials
initials = "nm"

# Date
date = datetime.now()

# Make a clean version string
version = f"{initials}-{date.strftime('%d%m%Y')}"
print(version)

nm-14072025

In [25]:
# suva_df = gpd.read_file("postcard_suva_dataframe.csv")
# yanuca_df = gpd.read_file("postcard_yanuca_dataframe.csv")
# korotogo_df = gpd.read_file("postcard_korotogo_dataframe.csv")
serua_df = gpd.read_file("training-data/nm-serua-14072025-training.csv")
# utanglang_df = gpd.read_file("postcard_utanglang_dataframe.csv")
# ba_df = gpd.read_file("postcard_ba_dataframe.csv")
bootless_df = gpd.read_file("training-data/nm-bootless_bay-13072025-training.csv")
# png_gabagaba_df = gpd.read_file("postcard_gabagaba_dataframe.csv")

In [26]:
serua_df.dtypes

cc_id          object
nir            object
red            object
blue           object
green          object
emad           object
smad           object
bcmad          object
count          object
nir08          object
nir09          object
swir16         object
swir22         object
coastal        object
rededge1       object
rededge2       object
rededge3       object
mndwi          object
ndti           object
cai            object
ndvi           object
evi            object
savi           object
ndwi           object
b_g            object
b_r            object
mci            object
ndci           object
ln_bg          object
contrast       object
homogeneity    object
energy         object
ASM            object
correlation    object
mean           object
entropy        object
y              object
x              object
time           object
spatial_ref    object
dtype: object

In [27]:
print(serua_df['cc_id'].value_counts())

cc_id
2    120
4     97
5     79
6     77
3     41
Name: count, dtype: int64

In [28]:
# Create sample GeoDataFrames
# postcards = [suva_df, yanuca_df, korotogo_df, serua_df, utanglang_df, ba_df, bootless_df, png_gabagaba_df]
# postcards = [suva_df, yanuca_df, korotogo_df, serua_df, utanglang_df, ba_df, png_gabagaba_df]
postcards = [serua_df, bootless_df]

In [29]:
for p in postcards:
    print(p.columns)

Index(['cc_id', 'nir', 'red', 'blue', 'green', 'emad', 'smad', 'bcmad',
       'count', 'nir08', 'nir09', 'swir16', 'swir22', 'coastal', 'rededge1',
       'rededge2', 'rededge3', 'mndwi', 'ndti', 'cai', 'ndvi', 'evi', 'savi',
       'ndwi', 'b_g', 'b_r', 'mci', 'ndci', 'ln_bg', 'contrast', 'homogeneity',
       'energy', 'ASM', 'correlation', 'mean', 'entropy', 'y', 'x', 'time',
       'spatial_ref'],
      dtype='object')
Index(['cc_id', 'nir', 'red', 'blue', 'green', 'emad', 'smad', 'bcmad',
       'count', 'nir08', 'nir09', 'swir16', 'swir22', 'coastal', 'rededge1',
       'rededge2', 'rededge3', 'mndwi', 'ndti', 'cai', 'ndvi', 'evi', 'savi',
       'ndwi', 'b_g', 'b_r', 'mci', 'ndci', 'ln_bg', 'contrast', 'homogeneity',
       'energy', 'ASM', 'correlation', 'mean', 'entropy', 'y', 'x', 'time',
       'spatial_ref'],
      dtype='object')

In [13]:
for p in postcards:
    print(p.shape[1], 'total columns')

40 total columns
40 total columns

In [14]:
# Check if the columns are the same
columns_same = set(bootless_df.columns) == set(serua_df.columns)

# Print the result
if columns_same:
    print("The columns in both GeoDataFrames are the same.")
else:
    print("The columns in the GeoDataFrames are different.")

The columns in both GeoDataFrames are the same.

In [15]:
standard_schema = ['cc_id', 'nir', 'red', 'blue', 'green', 'emad', 'smad', 'bcmad',
       'count', 'nir08', 'nir09', 'swir16', 'swir22', 'coastal', 'rededge1',
       'rededge2', 'rededge3', 'mndwi', 'ndti', 'cai', 'ndvi', 'evi', 'savi',
       'ndwi', 'b_g', 'b_r', 'mci', 'ndci', 'ln_bg', 'contrast', 'homogeneity',
       'energy', 'ASM', 'correlation', 'mean', 'entropy', 'y', 'x', 'time',
       'spatial_ref']

In [16]:
# bootless_df = bootless_df[standard_schema]
serua_df = bootless_df[standard_schema]

In [14]:
# Check if the columns are the same
columns_same = set(bootless_df.columns) == set(serua_df.columns)

# Print the result
if columns_same:
    print("The columns in both GeoDataFrames are the same.")
else:
    print("The columns in the GeoDataFrames are different.")

The columns in both GeoDataFrames are the same.

In [18]:
# joined_training_data = pd.concat([suva_df, yanuca_df, korotogo_df, serua_df, utanglang_df, ba_df, bootless_df, gabagaba_df], axis=0, ignore_index=True) # once we have more dataframes this code can be used to concatenate them
# joined_training_data = pd.concat([suva_df, yanuca_df, korotogo_df, serua_df, utanglang_df, ba_df, gabagaba_df], axis=0, ignore_index=True) # once we have more dataframes this code can be used to concatenate them
joined_tdata = pd.concat([serua_df, bootless_df])

In [19]:
joined_tdata

,cc_id,nir,red,blue,green,emad,smad,bcmad,count,nir08,...,homogeneity,energy,ASM,correlation,mean,entropy,y,x,time,spatial_ref
0,4,0.060200000000000004,0.0742,0.0926,0.1005,0.15210178,1.8036901e-06,3.3523716e-05,0.0031000000000000003,0.0637,...,0.8888889,0.5750067,0.33063272,0.55244756,3.5416667,1.7577515,-1057915.0,-302095.0,2024-01-01,0
1,4,0.059800000000000006,0.075,0.0989,0.1071,0.16122046,2.5572538e-06,3.372579e-05,0.0031000000000000003,0.0648,...,0.8680556,0.6616565,0.43778935,0.28283092,3.7569444,1.5470915,-1057915.0,-302075.0,2024-01-01,0
2,4,0.0597,0.075,0.0949,0.10400000000000001,0.16183805,2.51109e-06,3.397069e-05,0.0031000000000000003,0.06670000000000001,...,0.9513889,0.83904296,0.7039931,0.5331172,3.8819444,0.9105561,-1057945.0,-302075.0,2024-01-01,0
3,4,0.0597,0.0752,0.0952,0.10400000000000001,0.1583075,2.317196e-06,3.4195007e-05,0.0031000000000000003,0.06620000000000001,...,0.8958333,0.6366961,0.40538195,0.5151515,3.6875,1.6048688,-1057925.0,-302085.0,2024-01-01,0
4,4,0.058,0.0723,0.0995,0.10740000000000001,0.15900189,2.5702536e-06,3.435343e-05,0.0031000000000000003,0.06380000000000001,...,0.875,0.6947222,0.4826389,0.24210526,3.7916667,1.4387219,-1057915.0,-302065.0,2024-01-01,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,2,0.0658,0.1405,0.152,0.18480000000000002,0.13483694,3.050053e-06,2.590787e-05,0.0025,0.056600000000000004,...,0.80277777,0.6603433,0.43605325,0.6035124,2.5972223,2.2381856,-1057695.0,-302245.0,2024-01-01,0
383,2,0.0449,0.09280000000000001,0.10840000000000001,0.1283,0.105597325,2.4306833e-06,2.3776416e-05,0.0025,0.0417,...,0.775,0.57265353,0.3279321,0.78047067,3.0694444,2.6260667,-1057665.0,-302255.0,2024-01-01,0
384,2,0.0431,0.095,0.11810000000000001,0.1391,0.11168822,2.7728677e-06,2.0128533e-05,0.0025,0.0437,...,0.7708333,0.5891738,0.34712577,0.56151503,2.4930556,2.4821439,-1057635.0,-302235.0,2024-01-01,0
385,2,0.0487,0.1173,0.14200000000000002,0.1701,0.11532059,2.2951542e-06,2.138217e-05,0.0025,0.043300000000000005,...,0.8,0.62884617,0.39544752,0.5618661,2.4444444,2.2000573,-1057645.0,-302235.0,2024-01-01,0
386,2,0.051500000000000004,0.1139,0.13440000000000002,0.1612,0.11645156,3.0713736e-06,2.2657207e-05,0.0025,0.0488,...,0.7736111,0.63441974,0.40248844,0.68435675,2.6875,2.374747,-1057655.0,-302245.0,2024-01-01,0

In [21]:
joined_tdata.columns

Index(['cc_id', 'nir', 'red', 'blue', 'green', 'emad', 'smad', 'bcmad',
       'count', 'nir08', 'nir09', 'swir16', 'swir22', 'coastal', 'rededge1',
       'rededge2', 'rededge3', 'mndwi', 'ndti', 'cai', 'ndvi', 'evi', 'savi',
       'ndwi', 'b_g', 'b_r', 'mci', 'ndci', 'ln_bg', 'contrast', 'homogeneity',
       'energy', 'ASM', 'correlation', 'mean', 'entropy', 'y', 'x', 'time',
       'spatial_ref'],
      dtype='object')

In [26]:
# postcard_suva_df.columns
# joined_training_data = joined_training_data.drop(columns=["spatial_ref", "time", "field_1"])
joined_tdata = joined_tdata.drop(columns=["spatial_ref", "time", "count"])

In [31]:
joined_tdata.to_csv("training-data/"f"{version}-joined_tdata.csv", index=False)

In [28]:
# joined_training_data = joined_training_data[["uuid", "cc_id", "observed", "date", "geometry"]] #re-arranging the columns
joined_training_data

,cc_id,nir,red,blue,green,emad,smad,bcmad,count,nir08,...,ndvi,ndwi,mndwi,ndti,b_g,b_r,mci,ndci,y,x
0,2,0.0298,0.032899998,0.055999998,0.0436,0.08867363,4.070756e-06,3.3468114e-05,0.0058,0.0307,...,-0.049441766,0.18801092,0.24039832,-0.13986932,1.2844036,1.7021277,0.884273,0.012012049,-2044675.0,3153725.0
1,2,0.0295,0.0326,0.0559,0.043399997,0.08912841,3.7858456e-06,3.3206863e-05,0.0058,0.0307,...,-0.04991949,0.19067211,0.23646721,-0.14210522,1.2880185,1.714724,0.8727811,0.018072259,-2044665.0,3153725.0
2,2,0.0289,0.032199997,0.0552,0.042999998,0.08345044,3.5213677e-06,3.508021e-05,0.0056,0.0295,...,-0.05400979,0.19610569,0.2463768,-0.14361703,1.283721,1.7142859,0.8626865,0.019786963,-2044635.0,3153725.0
3,2,0.03,0.033299997,0.0565,0.0437,0.09336796,3.3604056e-06,3.2506323e-05,0.0058,0.0316,...,-0.052132674,0.18588874,0.22580643,-0.13506496,1.2929062,1.6966968,0.85470086,0.0263158,-2044655.0,3153725.0
4,2,0.0297,0.032199997,0.0563,0.0435,0.08827729,4.1538833e-06,3.362744e-05,0.0058,0.03,...,-0.040387686,0.18852457,0.24285713,-0.14927347,1.2942529,1.7484473,0.8839286,0.021276617,-2044695.0,3153725.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16513,8,0.057299998,0.0639,0.0799,0.076299995,0.13864477,1.4586091e-06,2.8264767e-05,0.003,0.062099997,...,-0.054455478,0.14221555,0.114682235,-0.088445045,1.0471822,1.2503911,0.8577844,0.022188196,-1057425.0,-302355.0
16514,8,0.050499998,0.055099998,0.072299995,0.067,0.11928381,1.1002033e-06,2.6359545e-05,0.003,0.0541,...,-0.0435606,0.14042556,0.13848773,-0.097461134,1.0791044,1.3121597,0.8767361,0.022182798,-1057625.0,-303005.0
16515,8,0.058,0.062299997,0.08,0.0744,0.11123463,1.1610985e-06,2.3864643e-05,0.0033,0.060999997,...,-0.03574396,0.12386708,0.11963883,-0.08851502,1.0752687,1.2841092,0.8787879,0.028838683,-1058355.0,-302925.0
16516,8,0.0547,0.058599997,0.073699996,0.0689,0.13072646,1.0475635e-06,2.6987886e-05,0.0029,0.057699997,...,-0.03442188,0.11488672,0.1095008,-0.080784306,1.0696661,1.2576792,0.89087945,0.023333356,-1058755.0,-302705.0
16517,8,0.0492,0.055,0.074,0.070199996,0.118337534,9.691953e-07,2.678764e-05,0.0029,0.053799998,...,-0.055662204,0.17587939,0.15650739,-0.12140572,1.0541312,1.3454546,0.86315787,0.017857146,-1058395.0,-301535.0

In [28]:
print(joined_training_data['cc_id'].nunique(),'unique classes')

8 unique classes

In [29]:
len(joined_training_data)

17025

In [30]:
print(joined_training_data['cc_id'].value_counts())

cc_id
8    5023
6    2490
2    2465
3    1923
4    1778
5    1588
1    1403
7     355
Name: count, dtype: int64

In [35]:
joined_training_data.dtypes

cc_id       float64
nir         float64
red         float64
blue        float64
green       float64
emad        float64
smad        float64
bcmad       float64
count       float64
nir08       float64
nir09       float64
swir16      float64
swir22      float64
coastal     float64
rededge1    float64
rededge2    float64
rededge3    float64
cai         float64
ndvi        float64
ndwi        float64
mndwi       float64
ndti        float64
b_g         float64
b_r         float64
mci         float64
ndci        float64
y           float64
x           float64
observed     object
dtype: object

In [32]:
joined_training_data = joined_training_data.astype(float)

In [36]:
# # Define two lists
# old_categories = ['sediment', 'sand', 'rubble', 'seagrass', 'seaweed', 'coral', 'rock', 'deeps', 'mangrove', 'land']
# new_groups = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# # Create the mapping dictionary
# category_mapping = dict(zip(old_categories, new_groups))

# # Apply mapping
# utanglang['observed'] = utanglang['cc_id'].map(category_mapping)

# utanglang

new_groups = ['sediment', 'sand', 'rubble', 'seagrass', 'seaweed', 'coral', 'rock', 'deeps', 'mangrove', 'land']
old_categories = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

category_mapping_2 = dict(zip(old_categories, new_groups))
joined_training_data['observed'] = joined_training_data['cc_id'].map(category_mapping_2)

# Print the result
# print(yanuca)

# Add unique ID
# Add date

In [37]:
joined_training_data['observed']=joined_training_data['observed'].astype(object)

In [38]:
print(joined_training_data['observed'].value_counts())

observed
deeps       5023
coral       2490
sand        2465
rubble      1923
seagrass    1778
seaweed     1588
sediment    1403
rock         355
Name: count, dtype: int64

In [40]:
joined_training_data = joined_training_data.rename(columns={"lulc": "observed", "class_id": "cc_id"})

In [41]:
joined_training_data

,cc_id,nir,red,blue,green,emad,smad,bcmad,count,nir08,...,ndwi,mndwi,ndti,b_g,b_r,mci,ndci,y,x,observed
0,2.0,0.0298,0.0329,0.0560,0.0436,0.088674,4.070756e-06,0.000033,0.0058,0.0307,...,0.188011,0.240398,-0.139869,1.284404,1.702128,0.884273,0.012012,-2044675.0,3153725.0,sand
1,2.0,0.0295,0.0326,0.0559,0.0434,0.089128,3.785846e-06,0.000033,0.0058,0.0307,...,0.190672,0.236467,-0.142105,1.288018,1.714724,0.872781,0.018072,-2044665.0,3153725.0,sand
2,2.0,0.0289,0.0322,0.0552,0.0430,0.083450,3.521368e-06,0.000035,0.0056,0.0295,...,0.196106,0.246377,-0.143617,1.283721,1.714286,0.862687,0.019787,-2044635.0,3153725.0,sand
3,2.0,0.0300,0.0333,0.0565,0.0437,0.093368,3.360406e-06,0.000033,0.0058,0.0316,...,0.185889,0.225806,-0.135065,1.292906,1.696697,0.854701,0.026316,-2044655.0,3153725.0,sand
4,2.0,0.0297,0.0322,0.0563,0.0435,0.088277,4.153883e-06,0.000034,0.0058,0.0300,...,0.188525,0.242857,-0.149273,1.294253,1.748447,0.883929,0.021277,-2044695.0,3153725.0,sand
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17020,8.0,0.0573,0.0639,0.0799,0.0763,0.138645,1.458609e-06,0.000028,0.0030,0.0621,...,0.142216,0.114682,-0.088445,1.047182,1.250391,0.857784,0.022188,-1057425.0,-302355.0,deeps
17021,8.0,0.0505,0.0551,0.0723,0.0670,0.119284,1.100203e-06,0.000026,0.0030,0.0541,...,0.140426,0.138488,-0.097461,1.079104,1.312160,0.876736,0.022183,-1057625.0,-303005.0,deeps
17022,8.0,0.0580,0.0623,0.0800,0.0744,0.111235,1.161099e-06,0.000024,0.0033,0.0610,...,0.123867,0.119639,-0.088515,1.075269,1.284109,0.878788,0.028839,-1058355.0,-302925.0,deeps
17023,8.0,0.0547,0.0586,0.0737,0.0689,0.130726,1.047564e-06,0.000027,0.0029,0.0577,...,0.114887,0.109501,-0.080784,1.069666,1.257679,0.890879,0.023333,-1058755.0,-302705.0,deeps
17024,8.0,0.0492,0.0550,0.0740,0.0702,0.118338,9.691953e-07,0.000027,0.0029,0.0538,...,0.175879,0.156507,-0.121406,1.054131,1.345455,0.863158,0.017857,-1058395.0,-301535.0,deeps